/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cntr;

import javax.swing.ImageIcon;

/**
 *This is the Menu JFrame which has three buttons to access to other JFrames
 * @author hayar.abderrafia
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/beekeeper.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonMembers = new javax.swing.JButton();
        jButtonExpenses = new javax.swing.JButton();
        jButtonMonthFee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Erlete Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Erlete management");

        jButtonMembers.setText("Members");
        jButtonMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMembersActionPerformed(evt);
            }
        });

        jButtonExpenses.setText("Expenses");

        jButtonMonthFee.setText("Month Fee");
        jButtonMonthFee.setActionCommand("monthFee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExpenses)
                            .addComponent(jButtonMembers)
                            .addComponent(jButtonMonthFee))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jButtonMembers)
                .addGap(29, 29, 29)
                .addComponent(jButtonMonthFee)
                .addGap(34, 34, 34)
                .addComponent(jButtonExpenses)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMembersActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonMembersActionPerformed

    /**
     * 
     * @return 
     */
    public static Menu viewaSortuBistaratu() {
        Menu m = new Menu();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                m.setVisible(true);
            }
        });
        return m;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonExpenses;
    public javax.swing.JButton jButtonMembers;
    public javax.swing.JButton jButtonMonthFee;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
